-- =============================================
-- MIGRATION: replace partial UNIQUE index on emails.resend_id with a
--            non-partial one so supabase-js .upsert(onConflict='resend_id')
--            actually works.
--
-- Why this is needed:
--   - The previous migration shipped:
--       CREATE UNIQUE INDEX uniq_emails_resend_id
--         ON emails(resend_id) WHERE resend_id IS NOT NULL;
--   - PostgreSQL requires that any INSERT ... ON CONFLICT (col) using a
--     PARTIAL index ALSO include the predicate in the inference clause:
--       ON CONFLICT (resend_id) WHERE resend_id IS NOT NULL DO NOTHING
--   - supabase-js .upsert(..., { onConflict: 'resend_id' }) generates
--     ON CONFLICT (resend_id) WITHOUT the WHERE. Postgres responds:
--       42P10  "there is no unique or exclusion constraint matching the
--               ON CONFLICT specification"
--   - The webhook (app/api/webhook/email/route.js) and the sync script
--     both rely on this. Webhook is currently rejecting every
--     email.received delivery with HTTP 500 Insert failed in production.
--
-- Why a non-partial UNIQUE is safe:
--   - PostgreSQL treats NULL as distinct in UNIQUE indexes (UNIQUE NULLS
--     DISTINCT is the default), so the 344+ existing rows where
--     resend_id IS NULL (all outbound rows generated by the app) remain
--     legal under the new index.
--   - Verified before this migration: 0 duplicate non-NULL resend_id in
--     production at the moment of the change.
--
-- Safety:
--   - DROP INDEX is fast (metadata-only) and CREATE UNIQUE INDEX takes
--     a brief AccessExclusiveLock on emails while it builds — at the
--     scale of this table (<1000 rows) this is sub-second.
--   - NOTIFY pgrst 'reload schema' forces PostgREST to refresh its
--     cached schema; without it the new constraint isn't visible to the
--     REST layer and the same 42P10 error continues for ~10 minutes.
--   - Reversible by re-creating the partial form: see comment at the
--     bottom for the rollback script.
-- =============================================

BEGIN;

DROP INDEX IF EXISTS public.uniq_emails_resend_id;

CREATE UNIQUE INDEX uniq_emails_resend_id
  ON public.emails(resend_id);

COMMIT;

NOTIFY pgrst, 'reload schema';

-- Rollback (only if you really need to go back to the partial form):
--   BEGIN;
--   DROP INDEX IF EXISTS public.uniq_emails_resend_id;
--   CREATE UNIQUE INDEX uniq_emails_resend_id
--     ON public.emails(resend_id) WHERE resend_id IS NOT NULL;
--   COMMIT;
--   NOTIFY pgrst, 'reload schema';
